export default interface appState {
  numOfSkills: number
  hasSkill1?: boolean
  hasSkill2?: boolean
  hasSkill3?: boolean
  hasSkill4?: boolean
  hasSkill5?: boolean
  hasSkill6?: boolean
  hasSkill7?: boolean
  hasSkill8?: boolean
  hasSkill9?: boolean
  firstName?: string
  lastName?: string
  title?: string
  photoSrc?: string
  address?: string
  phoneNumber?: string
  email?: string
  description?: string
  uniName?: string
  uniCity?: string
  uniDegree?: string
  uniSubject?: string
  uniFrom?: string
  uniTo?: string
  gitHub?: string
  webPage?: string
  skill1?: string
  skill2?: string
  skill3?: string
  skill4?: string
  skill5?: string
  skill6?: string
  skill7?: string
  skill8?: string
  skill9?: string
  skill1Src?: string
  skill2Src?: string
  skill3Src?: string
  skill4Src?: string
  skill5Src?: string
  skill6Src?: string
  skill7Src?: string
  skill8Src?: string
  skill9Src?: string
  numOfPages: number
  page1Dom?: string
  page1Url?: string
  page1Src?: string
  page2Dom?: string
  page2Url?: string
  page2Src?: string
  page3Dom?: string
  page3Url?: string
  page3Src?: string
  page4Dom?: string
  page4Url?: string
  page4Src?: string
  hasPage1?: boolean
  hasPage2?: boolean
  hasPage3?: boolean
  hasPage4?: boolean
}
